version: '3'

services:
  web:
    build:
      context: ../  # Ruta relativa al Dockerfile
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app/:/app/  # Montar el código en el contenedor
