# Generated by Django 4.2.4 on 2023-08-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='', upload_to='static/album_photo/'),
        ),
    ]
